# Generated by Django 2.2.2 on 2019-06-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='stock',
            new_name='stock_level',
        ),
    ]
